credentials:
    some_value_here: not_a_secret
    other_value_here: 1234567890a
    nested:
        value: AKIAabcdefghijklmnop
        value: abcdefghijklmnop
list_of_keys:
    - 123
    - 456
    - 234567890a

test_agent::whitelisted_api_key: 'ToCynx5Se4e2PtoZxEhW7lUJcOX15c54'  # pragma: whitelist secret
